title: Snaptics
theme: minima

header_pages:
  - pages/tutorials.md
  - pages/hardware.md
  - pages/electronics.md
  - pages/FAQ.md
  - pages/aboutus.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
