title: Snaptics

minima:
  skin: solarized-dark

header_pages:
  - pages/tutorials.md
  - pages/hardware.md
  - pages/electronics.md
  - pages/software.md
  - pages/FAQ.md
  - pages/aboutus.md

theme: minima

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
